name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install libpcap-dev
      run: sudo apt update && sudo apt-get -q -y  install libpcap-dev

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v ./...; go build -v -o speeve cmd/speeve/main.go

    - name: Test
      run: go test -v ./...

    - name: Provide binary as artifact
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: speeve-executable
        path: speeve